---
- hosts: labhosts,prodhosts

  vars:
    foo: bar
    package_list:
      - at
      - vim
      - curl
      - python-pip
      - git


  tasks:
  - name: cmd-hostname
    command:
      cmd: 'hostname'
    register: response

  - name: dir-/etc/baseline
    become: yes
    file:
      path: /etc/baseline
      state: directory
      mode: '0755'

  - name: filetemplate-/etc/baseline/bashrc
    become: yes
    template:
      src: templates/bashrc
      dest: /etc/baseline/bashrc
      owner: root
      group: root
      mode: '0644'

  - name: blockinsert-/etc/bash.bashrc
    become: yes
    blockinfile:
      path: /etc/bash.bashrc
      block: |
        # append cm-based rc files:
        if [ -f /etc/baseline/bashrc ]; then
           source /etc/baseline/bashrc
        fi

  - name: check-folders-/installers
    stat:
      path: /installers
    register: result_check_installers

  - name: show-check-folders
    debug:
      msg: 'stats result: {{ result_check_installers }}'

  - name: dir-create-/srv/installers
    become: yes
    file:
      path: /srv/installers
      state: directory
      mode: '0755'
    when: not result_check_installers.stat.exists

  - name: symlink-create-/installers-pointingto-/srv/installers
    become: yes
    file:
      src: /srv/installers
      dest: /installers
      owner: root
      group: root
      state: link
      force: yes
    when: not result_check_installers.stat.exists

  - name: symlink-create-/srv/installers-pointingto-/installers
    become: yes
    file:
      src: /installers
      dest: /srv/installers
      owner: root
      group: root
      state: link
      force: yes
    when:
      - result_check_installers.stat.exists
      - result_check_installers.stat.isdir

  # TODO: chain this to run as a Prerequisite for package-installs
  - name: cmd-update-repo-catalog
    become: yes
    command:
      cmd: 'apt-get update'

  - name: package-installs
    become: yes
    package:
      name: "{{ package_list }}"
      state: present
