---
- hosts: linux_all

  vars:
    vimrc_web_url: 'https://raw.githubusercontent.com/voytekio/rc_files/master/vimrc'
    package_list:
      - at
      - vim
      - curl
      - git
    package_list_ubuntu:
      - python3-pip
      - python3-venv


  tasks:
  - name: cmd-hostname
    command:
      cmd: 'hostname'
    register: response

  - name: Show facts available on the system
    ansible.builtin.debug:
      var: ansible_facts
    when: 1 == 2

  - name: fail early
    fail:
      msg: 'failing early'
    when: 2 == 1

  - name: dir-/etc/baseline
    become: yes
    file:
      path: /etc/baseline
      state: directory
      mode: '0755'

  - name: filetemplate-/etc/baseline/bashrc
    become: yes
    template:
      src: templates/bashrc
      dest: /etc/baseline/bashrc
      owner: root
      group: root
      mode: '0644'

  - name: blockinsert-/etc/bashrc
    become: yes
    blockinfile:
      path: /etc/bashrc
      block: |
        # append cm-based rc files:
        if [ -f /etc/baseline/bashrc ]; then
           source /etc/baseline/bashrc
        fi
    when: ansible_facts['os_family'] == 'RedHat'

  - name: blockinsert-/etc/bash.bashrc
    become: yes
    blockinfile:
      path: /etc/bash.bashrc
      block: |
        # append cm-based rc files:
        if [ -f /etc/baseline/bashrc ]; then
           source /etc/baseline/bashrc
        fi
    when: ansible_facts['os_family'] == 'Debian'

  - name: copy vimrc from github
    get_url:
      url: 'https://raw.githubusercontent.com/voytekio/rc_files/master/vimrc'
      dest: '{{ ansible_facts.env.HOME }}/.vimrc'
      mode: '0664'

  - name: check-folders-/installers
    stat:
      path: /installers
    register: result_check_installers

  - name: show-check-folders
    debug:
      msg: 'stats result: {{ result_check_installers }}'

  - name: dir-create-/srv/installers
    become: yes
    file:
      path: /srv/installers
      state: directory
      mode: '0755'
    when: not result_check_installers.stat.exists

  - name: symlink-create-/installers-pointingto-/srv/installers
    become: yes
    file:
      src: /srv/installers
      dest: /installers
      owner: root
      group: root
      state: link
      force: yes
    when: not result_check_installers.stat.exists

  - name: symlink-create-/srv/installers-pointingto-/installers
    become: yes
    file:
      src: /installers
      dest: /srv/installers
      owner: root
      group: root
      state: link
      force: yes
    when:
      - result_check_installers.stat.exists
      - result_check_installers.stat.isdir

  # TODO: chain this to run as a Prerequisite for package-installs
  - name: cmd-update-repo-catalog
    become: yes
    command:
      cmd: 'apt-get update'
    when: ansible_facts['os_family'] == 'Debian'

  - name: package-installs
    become: yes
    package:
      name: "{{ package_list }}"
      state: present

  - name: package-installs-ubuntu
    become: yes
    package:
      name: "{{ package_list_ubuntu }}"
      state: present
    when: ansible_facts['os_family'] == 'Debian'
