---
- hosts: labhosts

  vars:
    foo: bar

  tasks:
  - name: show some output on screen
    debug:
        msg: 'value of foo var is ---> {{ foo }}'

  - name: try a cmd
    win_shell: 'hostname'
    register: response

  - name: show hostname result
    debug:
      msg: 'hostname result is:\n{{ response }}'

  - name: install windows server backup
    ansible.windows.win_feature:
      name: Windows-Server-Backup
      state: present
      include_management_tools: true
  - name: install vpn
    ansible.windows.win_feature:
      name: DirectAccess-VPN
      state: present
      include_management_tools: true
