---
- hosts: win_servers

  vars:
    - backup_target: 'd:'
    - backup_marker_file_loc: 'backup_marker_file.txt'
  vars_prompt:
    - name: ansible_password
      prompt: 'admin pass'
      private: yes

  tasks:
  - name: add a marker to file to use for backup verification
    ansible.windows.win_shell: 'add-content -path {{ backup_marker_file_loc }} -value {{ "%Y-%m-%d-%H-%M-%S" | strftime( (ansible_facts["date_time"]["epoch_local"] | int ))  }}'

  - name: run a win command (no shell)
    ansible.windows.win_shell: 'wbadmin start backup -backuptarget:{{ backup_target }} -allcritical -quiet >> winbackup.log'
    #async: 45
    #poll: 0
